namespace Railwind.Enums;

public enum MaxWidth
{
    Zero = 1,
    One = 2,
    Two = 3,
    Three = 4,
    Four = 5,
    Five = 6,
    Six = 7,
    Seven = 8,
    Eight = 9,
    Nine = 10,
    Ten = 11,
    Eleven = 12,
    Twelve = 13,
    Fourteen = 14,
    Sixteen = 15,
    Twenty = 16,
    TwentyFour = 17,
    TwentyEight = 18,
    ThirtyTwo = 19,
    ThirtySix = 20,
    Forty = 21,
    FortyFour = 22,
    FortyEight = 23,
    FiftyTwo = 24,
    FiftySix = 25,
    Sixty = 26,
    SixtyFour = 27,
    SeventyTwo = 28,
    Eighty = 29,
    NinetySix = 30,
    ZeroPointFive = 31,
    OnePointFive = 32,
    TwoPointFive = 33,
    ThreePointFive = 34,
    Full = 35,
    ThreeXs,
    TwoXs,
    Xs,
    Sm,
    Md,
    Lg,
    Xl,
    TwoXl,
    ThreeXl,
    FourXl,
    FiveXl,
    SixXl,
    SevenXl
}