using Railwind.Common.Enums;
using Railwind.Enums;
using Railwind.Features.Themes;

namespace Railwind.Common.Extensions;

public static class ColorExtensions
{
    /// <summary>
    /// Combines a color and weight to generate a Tailwind CSS text color class (e.g., "text-gray-900").
    /// </summary>
    /// <param name="color">The Tailwind color (e.g., Colors.Gray).</param>
    /// <param name="weight">The weight or shade (e.g., Weight.Weight900).</param>
    /// <returns>A Tailwind text color class string (e.g., "text-gray-900").</returns>
    public static string ToTextColor(this Colors color, Weight weight)
    {
        // Convert color enum to lowercase Tailwind color name
        string colorName = color.ToString().ToLower();

        // Extract the numeric weight value (e.g., Weight900 -> 900)
        int weightValue = (int)weight;

        // Return formatted Tailwind text color class
        return $"text-{colorName}-{weightValue}";
    }
    



    public static string ToTextColorDarkWeight400LightWeight800(this Colors color) => color switch
    {
        Colors.Black => "text-black",
        Colors.White => "text-white",
        Colors.Slate => "text-slate-800 dark:text-slate-400",
        Colors.Gray => "text-gray-800 dark:text-gray-400",
        Colors.Zinc => "text-zinc-800 dark:text-zinc-400",
        Colors.Neutral => "text-neutral-800 dark:text-neutral-400",
        Colors.Stone => "text-stone-800 dark:text-stone-400",
        Colors.Red => "text-red-800 dark:text-red-400",
        Colors.Orange => "text-orange-800 dark:text-orange-400",
        Colors.Amber => "text-amber-800 dark:text-amber-400",
        Colors.Yellow => "text-yellow-800 dark:text-yellow-400",
        Colors.Lime => "text-lime-800 dark:text-lime-400",
        Colors.Green => "text-green-800 dark:text-green-400",
        Colors.Emerald => "text-emerald-800 dark:text-emerald-400",
        Colors.Teal => "text-teal-800 dark:text-teal-400",
        Colors.Cyan => "text-cyan-800 dark:text-cyan-400",
        Colors.Sky => "text-sky-800 dark:text-sky-400",
        Colors.Blue => "text-blue-800 dark:text-blue-400",
        Colors.Indigo => "text-indigo-800 dark:text-indigo-400",
        Colors.Violet => "text-violet-800 dark:text-violet-400",
        Colors.Purple => "text-purple-800 dark:text-purple-400",
        Colors.Fuchsia => "text-fuchsia-800 dark:text-fuchsia-400",
        Colors.Pink => "text-pink-800 dark:text-pink-400",
        Colors.Rose => "text-rose-800 dark:text-rose-400",
        Colors.AthensGray => "text-athens-gray-800 dark:text-athens-gray-400",
        Colors.Woodsmoke => "text-woodsmoke-800 dark:text-woodsmoke-400",
        Colors.TurkishRose => "text-turkish-rose-800 dark:text-turkish-rose-400",
        _ => ""
    };
    
    public static string ToTextColorWeight600(this Colors color) => color switch
    {
        Colors.Black => "text-black",
        Colors.White => "text-white",
        Colors.Slate => "text-slate-600",
        Colors.Gray => "text-gray-600",
        Colors.Zinc => "text-zinc-600",
        Colors.Neutral => "text-neutral-600",
        Colors.Stone => "text-stone-600",
        Colors.Red => "text-red-600",
        Colors.Orange => "text-orange-600",
        Colors.Amber => "text-amber-600",
        Colors.Yellow => "text-yellow-600",
        Colors.Lime => "text-lime-600",
        Colors.Green => "text-green-600",
        Colors.Emerald => "text-emerald-600",
        Colors.Teal => "text-teal-600",
        Colors.Cyan => "text-cyan-600",
        Colors.Sky => "text-sky-600",
        Colors.Blue => "text-blue-600",
        Colors.Indigo => "text-indigo-600",
        Colors.Violet => "text-violet-600",
        Colors.Purple => "text-purple-600",
        Colors.Fuchsia => "text-fuchsia-600",
        Colors.Pink => "text-pink-600",
        Colors.Rose => "text-rose-600",
        Colors.AthensGray => "text-athens-gray-600",
        Colors.Woodsmoke => "text-woodsmoke-600",
        Colors.TurkishRose => "text-turkish-rose-600",
        _ => "text-gray-600"
    };
    
    public static string ToTextColorWeight800(this Colors color) => color switch
    {
        Colors.Black => "text-black",
        Colors.White => "text-white",
        Colors.Slate => "text-slate-800",
        Colors.Gray => "text-gray-800",
        Colors.Zinc => "text-zinc-800",
        Colors.Neutral => "text-neutral-800",
        Colors.Stone => "text-stone-800",
        Colors.Red => "text-red-800",
        Colors.Orange => "text-orange-800",
        Colors.Amber => "text-amber-800",
        Colors.Yellow => "text-yellow-800",
        Colors.Lime => "text-lime-800",
        Colors.Green => "text-green-800",
        Colors.Emerald => "text-emerald-800",
        Colors.Teal => "text-teal-800",
        Colors.Cyan => "text-cyan-800",
        Colors.Sky => "text-sky-800",
        Colors.Blue => "text-blue-800",
        Colors.Indigo => "text-indigo-800",
        Colors.Violet => "text-violet-800",
        Colors.Purple => "text-purple-800",
        Colors.Fuchsia => "text-fuchsia-800",
        Colors.Pink => "text-pink-800",
        Colors.Rose => "text-rose-800",
        Colors.AthensGray => "text-athens-gray-800",
        Colors.Woodsmoke => "text-woodsmoke-800",
        Colors.TurkishRose => "text-turkish-rose-800",
        _ => ""
    };
    
    public static string ToHoverBorderColorWeight300(this Colors color) => color switch
    {
        Colors.Black => "hover:border-black",
        Colors.White => "hover:border-white",
        Colors.Slate => "hover:border-slate-300",
        Colors.Gray => "hover:border-gray-300",
        Colors.Zinc => "hover:border-zinc-300",
        Colors.Neutral => "hover:border-neutral-300",
        Colors.Stone => "hover:border-stone-300",
        Colors.Red => "hover:border-red-300",
        Colors.Orange => "hover:border-orange-300",
        Colors.Amber => "hover:border-amber-300",
        Colors.Yellow => "hover:border-yellow-300",
        Colors.Lime => "hover:border-lime-300",
        Colors.Green => "hover:border-green-300",
        Colors.Emerald => "hover:border-emerald-300",
        Colors.Teal => "hover:border-teal-300",
        Colors.Cyan => "hover:border-cyan-300",
        Colors.Sky => "hover:border-sky-300",
        Colors.Blue => "hover:border-blue-300",
        Colors.Indigo => "hover:border-indigo-300",
        Colors.Violet => "hover:border-violet-300",
        Colors.Purple => "hover:border-purple-300",
        Colors.Fuchsia => "hover:border-fuchsia-300",
        Colors.Pink => "hover:border-pink-300",
        Colors.Rose => "hover:border-rose-300",
        Colors.AthensGray => "hover:border-athens-gray-300",
        Colors.Woodsmoke => "hover:border-woodsmoke-300",
        Colors.TurkishRose => "hover:border-turkish-rose-300",
        _ => "hover:border-gray-300"
    };
    
    public static string ToHoverTextColorWeight700(this Colors color) => color switch
    {
        Colors.Black => "hover:text-black",
        Colors.White => "hover:text-white",
        Colors.Slate => "hover:text-slate-700",
        Colors.Gray => "hover:text-gray-700",
        Colors.Zinc => "hover:text-zinc-700",
        Colors.Neutral => "hover:text-neutral-700",
        Colors.Stone => "hover:text-stone-700",
        Colors.Red => "hover:text-red-700",
        Colors.Orange => "hover:text-orange-700",
        Colors.Amber => "hover:text-amber-700",
        Colors.Yellow => "hover:text-yellow-700",
        Colors.Lime => "hover:text-lime-700",
        Colors.Green => "hover:text-green-700",
        Colors.Emerald => "hover:text-emerald-700",
        Colors.Teal => "hover:text-teal-700",
        Colors.Cyan => "hover:text-cyan-700",
        Colors.Sky => "hover:text-sky-700",
        Colors.Blue => "hover:text-blue-700",
        Colors.Indigo => "hover:text-indigo-700",
        Colors.Violet => "hover:text-violet-700",
        Colors.Purple => "hover:text-purple-700",
        Colors.Fuchsia => "hover:text-fuchsia-700",
        Colors.Pink => "hover:text-pink-700",
        Colors.Rose => "hover:text-rose-700",
        Colors.AthensGray => "hover:text-athens-gray-700",
        Colors.Woodsmoke => "hover:text-woodsmoke-700",
        Colors.TurkishRose => "hover:text-turkish-rose-700",
        _ => "hover:text-gray-700"
    };
    
    public static string ToBorderColorWeight500(this Colors color) => color switch
    {
        Colors.Black => "border-black",
        Colors.White => "border-white",
        Colors.Slate => "border-slate-500",
        Colors.Gray => "border-gray-500",
        Colors.Zinc => "border-zinc-500",
        Colors.Neutral => "border-neutral-500",
        Colors.Stone => "border-stone-500",
        Colors.Red => "border-red-500",
        Colors.Orange => "border-orange-500",
        Colors.Amber => "border-amber-500",
        Colors.Yellow => "border-yellow-500",
        Colors.Lime => "border-lime-500",
        Colors.Green => "border-green-500",
        Colors.Emerald => "border-emerald-500",
        Colors.Teal => "border-teal-500",
        Colors.Cyan => "border-cyan-500",
        Colors.Sky => "border-sky-500",
        Colors.Blue => "border-blue-500",
        Colors.Indigo => "border-indigo-500",
        Colors.Violet => "border-violet-500",
        Colors.Purple => "border-purple-500",
        Colors.Fuchsia => "border-fuchsia-500",
        Colors.Pink => "border-pink-500",
        Colors.Rose => "border-rose-500",
        Colors.AthensGray => "border-athens-gray-500",
        Colors.Woodsmoke => "border-woodsmoke-500",
        Colors.TurkishRose => "border-turkish-rose-500",
        _ => "border-gray-500"
    };
    
    public static string ToTextColorWeight400(this Colors color) => color switch
    {
        Colors.Black => "text-black",
        Colors.White => "text-white",
        Colors.Slate => "text-slate-400",
        Colors.Gray => "text-gray-400",
        Colors.Zinc => "text-zinc-400",
        Colors.Neutral => "text-neutral-400",
        Colors.Stone => "text-stone-400",
        Colors.Red => "text-red-400",
        Colors.Orange => "text-orange-400",
        Colors.Amber => "text-amber-400",
        Colors.Yellow => "text-yellow-400",
        Colors.Lime => "text-lime-400",
        Colors.Green => "text-green-400",
        Colors.Emerald => "text-emerald-400",
        Colors.Teal => "text-teal-400",
        Colors.Cyan => "text-cyan-400",
        Colors.Sky => "text-sky-400",
        Colors.Blue => "text-blue-400",
        Colors.Indigo => "text-indigo-400",
        Colors.Violet => "text-violet-400",
        Colors.Purple => "text-purple-400",
        Colors.Fuchsia => "text-fuchsia-400",
        Colors.Pink => "text-pink-400",
        Colors.Rose => "text-rose-400",
        Colors.AthensGray => "text-athens-gray-400",
        Colors.Woodsmoke => "text-woodsmoke-400",
        Colors.TurkishRose => "text-turkish-rose-400",
        _ => ""
    };

    public static string ToBackgroundColorWeight400WithOpacity10(this Colors color) => color switch
    {
        Colors.Black => "bg-black",
        Colors.White => "bg-white",
        Colors.Slate => "bg-slate-400/10",
        Colors.Gray => "bg-gray-400/10",
        Colors.Zinc => "bg-zinc-400/10",
        Colors.Neutral => "bg-neutral-400/10",
        Colors.Stone => "bg-stone-400/10",
        Colors.Red => "bg-red-400/10",
        Colors.Orange => "bg-orange-400/10",
        Colors.Amber => "bg-amber-400/10",
        Colors.Yellow => "bg-yellow-400/10",
        Colors.Lime => "bg-lime-400/10",
        Colors.Green => "bg-green-400/10",
        Colors.Emerald => "bg-emerald-400/10",
        Colors.Teal => "bg-teal-400/10",
        Colors.Cyan => "bg-cyan-400/10",
        Colors.Sky => "bg-sky-400/10",
        Colors.Blue => "bg-blue-400/10",
        Colors.Indigo => "bg-indigo-400/10",
        Colors.Violet => "bg-violet-400/10",
        Colors.Purple => "bg-purple-400/10",
        Colors.Fuchsia => "bg-fuchsia-400/10",
        Colors.Pink => "bg-pink-400/10",
        Colors.Rose => "bg-rose-400/10",
        Colors.AthensGray => "bg-athens-gray-400/10",
        Colors.Woodsmoke => "bg-woodsmoke-400/10",
        Colors.TurkishRose => "bg-turkish-rose-400/10",
        _ => ""
    };
    
    public static string ToBackgroundColorWeight500(this Colors color) => color switch
    {
        Colors.Black => "bg-black",
        Colors.White => "bg-white",
        Colors.Slate => "bg-slate-500",
        Colors.Gray => "bg-gray-500",
        Colors.Zinc => "bg-zinc-500",
        Colors.Neutral => "bg-neutral-500",
        Colors.Stone => "bg-stone-500",
        Colors.Red => "bg-red-500",
        Colors.Orange => "bg-orange-500",
        Colors.Amber => "bg-amber-500",
        Colors.Yellow => "bg-yellow-500",
        Colors.Lime => "bg-lime-500",
        Colors.Green => "bg-green-500",
        Colors.Emerald => "bg-emerald-500",
        Colors.Teal => "bg-teal-500",
        Colors.Cyan => "bg-cyan-500",
        Colors.Sky => "bg-sky-500",
        Colors.Blue => "bg-blue-500",
        Colors.Indigo => "bg-indigo-500",
        Colors.Violet => "bg-violet-500",
        Colors.Purple => "bg-purple-500",
        Colors.Fuchsia => "bg-fuchsia-500",
        Colors.Pink => "bg-pink-500",
        Colors.Rose => "bg-rose-500",
        Colors.AthensGray => "bg-athens-gray-500",
        Colors.Woodsmoke => "bg-woodsmoke-500",
        Colors.TurkishRose => "bg-turkish-rose-500",
        _ => ""
    };
    
    public static string ToBackgroundColorWeight600(this Colors color) => color switch
    {
        Colors.Black => "bg-black",
        Colors.White => "bg-white",
        Colors.Slate => "bg-slate-600",
        Colors.Gray => "bg-gray-600",
        Colors.Zinc => "bg-zinc-600",
        Colors.Neutral => "bg-neutral-600",
        Colors.Stone => "bg-stone-600",
        Colors.Red => "bg-red-600",
        Colors.Orange => "bg-orange-600",
        Colors.Amber => "bg-amber-600",
        Colors.Yellow => "bg-yellow-600",
        Colors.Lime => "bg-lime-600",
        Colors.Green => "bg-green-600",
        Colors.Emerald => "bg-emerald-600",
        Colors.Teal => "bg-teal-600",
        Colors.Cyan => "bg-cyan-600",
        Colors.Sky => "bg-sky-600",
        Colors.Blue => "bg-blue-600",
        Colors.Indigo => "bg-indigo-600",
        Colors.Violet => "bg-violet-600",
        Colors.Purple => "bg-purple-600",
        Colors.Fuchsia => "bg-fuchsia-600",
        Colors.Pink => "bg-pink-600",
        Colors.Rose => "bg-rose-600",
        Colors.AthensGray => "bg-athens-gray-600",
        Colors.Woodsmoke => "bg-woodsmoke-600",
        Colors.TurkishRose => "bg-turkish-rose-600",
        _ => ""
    };
    
    public static string ToBackgroundColorWeight700(this Colors color) => color switch
    {
        Colors.Black => "bg-black",
        Colors.White => "bg-white",
        Colors.Slate => "bg-slate-700",
        Colors.Gray => "bg-gray-700",
        Colors.Zinc => "bg-zinc-700",
        Colors.Neutral => "bg-neutral-700",
        Colors.Stone => "bg-stone-700",
        Colors.Red => "bg-red-700",
        Colors.Orange => "bg-orange-700",
        Colors.Amber => "bg-amber-700",
        Colors.Yellow => "bg-yellow-700",
        Colors.Lime => "bg-lime-700",
        Colors.Green => "bg-green-700",
        Colors.Emerald => "bg-emerald-700",
        Colors.Teal => "bg-teal-700",
        Colors.Cyan => "bg-cyan-700",
        Colors.Sky => "bg-sky-700",
        Colors.Blue => "bg-blue-700",
        Colors.Indigo => "bg-indigo-700",
        Colors.Violet => "bg-violet-700",
        Colors.Purple => "bg-purple-700",
        Colors.Fuchsia => "bg-fuchsia-700",
        Colors.Pink => "bg-pink-700",
        Colors.Rose => "bg-rose-700",
        Colors.AthensGray => "bg-athens-gray-700",
        Colors.Woodsmoke => "bg-woodsmoke-700",
        Colors.TurkishRose => "bg-turkish-rose-700",
        _ => ""
    };
    
    public static string ToBackgroundColorWeight900WithOpacity20(this Colors color) => color switch
    {
        Colors.Black => "bg-black",
        Colors.White => "bg-white",
        Colors.Slate => "bg-slate-900/20",
        Colors.Gray => "bg-gray-900/20",
        Colors.Zinc => "bg-zinc-900/20",
        Colors.Neutral => "bg-neutral-900/20",
        Colors.Stone => "bg-stone-900/20",
        Colors.Red => "bg-red-900/20",
        Colors.Orange => "bg-orange-900/20",
        Colors.Amber => "bg-amber-900/20",
        Colors.Yellow => "bg-yellow-900/20",
        Colors.Lime => "bg-lime-900/20",
        Colors.Green => "bg-green-900/20",
        Colors.Emerald => "bg-emerald-900/20",
        Colors.Teal => "bg-teal-900/20",
        Colors.Cyan => "bg-cyan-900/20",
        Colors.Sky => "bg-sky-900/20",
        Colors.Blue => "bg-blue-900/20",
        Colors.Indigo => "bg-indigo-900/20",
        Colors.Violet => "bg-violet-900/20",
        Colors.Purple => "bg-purple-900/20",
        Colors.Fuchsia => "bg-fuchsia-900/20",
        Colors.Pink => "bg-pink-900/20",
        Colors.Rose => "bg-rose-900/20",
        Colors.AthensGray => "bg-athens-gray-900/20",
        Colors.Woodsmoke => "bg-woodsmoke-900/20",
        Colors.TurkishRose => "bg-turkish-rose-900/20",
        _ => ""
    };
    
    public static string ToHoverBackgroundColorWeight900WithOpacity40(this Colors color) => color switch
    {
        Colors.Black => "hover:bg-black",
        Colors.White => "hover:bg-white",
        Colors.Slate => "hover:bg-slate-900/40",
        Colors.Gray => "hover:bg-gray-900/40",
        Colors.Zinc => "hover:bg-zinc-900/40",
        Colors.Neutral => "hover:bg-neutral-900/40",
        Colors.Stone => "hover:bg-stone-900/40",
        Colors.Red => "hover:bg-red-900/40",
        Colors.Orange => "hover:bg-orange-900/40",
        Colors.Amber => "hover:bg-amber-900/40",
        Colors.Yellow => "hover:bg-yellow-900/40",
        Colors.Lime => "hover:bg-lime-900/40",
        Colors.Green => "hover:bg-green-900/40",
        Colors.Emerald => "hover:bg-emerald-900/40",
        Colors.Teal => "hover:bg-teal-900/40",
        Colors.Cyan => "hover:bg-cyan-900/40",
        Colors.Sky => "hover:bg-sky-900/40",
        Colors.Blue => "hover:bg-blue-900/40",
        Colors.Indigo => "hover:bg-indigo-900/40",
        Colors.Violet => "hover:bg-violet-900/40",
        Colors.Purple => "hover:bg-purple-900/40",
        Colors.Fuchsia => "hover:bg-fuchsia-900/40",
        Colors.Pink => "hover:bg-pink-900/40",
        Colors.Rose => "hover:bg-rose-900/40",
        Colors.AthensGray => "hover:bg-athens-gray-900/40",
        Colors.Woodsmoke => "hover:bg-woodsmoke-900/40",
        Colors.TurkishRose => "hover:bg-turkish-rose-900/40",
        _ => ""
    };
    
    public static string ToHoverBackgroundColorWeight600(this Colors color) => color switch
    {
        Colors.Black => "hover:bg-black",
        Colors.White => "hover:bg-white",
        Colors.Slate => "hover:bg-slate-600",
        Colors.Gray => "hover:bg-gray-600",
        Colors.Zinc => "hover:bg-zinc-600",
        Colors.Neutral => "hover:bg-neutral-600",
        Colors.Stone => "hover:bg-stone-600",
        Colors.Red => "hover:bg-red-600",
        Colors.Orange => "hover:bg-orange-600",
        Colors.Amber => "hover:bg-amber-600",
        Colors.Yellow => "hover:bg-yellow-600",
        Colors.Lime => "hover:bg-lime-600",
        Colors.Green => "hover:bg-green-600",
        Colors.Emerald => "hover:bg-emerald-600",
        Colors.Teal => "hover:bg-teal-600",
        Colors.Cyan => "hover:bg-cyan-600",
        Colors.Sky => "hover:bg-sky-600",
        Colors.Blue => "hover:bg-blue-600",
        Colors.Indigo => "hover:bg-indigo-600",
        Colors.Violet => "hover:bg-violet-600",
        Colors.Purple => "hover:bg-purple-600",
        Colors.Fuchsia => "hover:bg-fuchsia-600",
        Colors.Pink => "hover:bg-pink-600",
        Colors.Rose => "hover:bg-rose-600",
        Colors.AthensGray => "hover:bg-athens-gray-600",
        Colors.Woodsmoke => "hover:bg-woodsmoke-600",
        Colors.TurkishRose => "hover:bg-turkish-rose-600",
        _ => ""
    };
    
    public static string ToHoverBackgroundColorWeight700(this Colors color) => color switch
    {
        Colors.Black => "hover:bg-black",
        Colors.White => "hover:bg-white",
        Colors.Slate => "hover:bg-slate-700",
        Colors.Gray => "hover:bg-gray-700",
        Colors.Zinc => "hover:bg-zinc-700",
        Colors.Neutral => "hover:bg-neutral-700",
        Colors.Stone => "hover:bg-stone-700",
        Colors.Red => "hover:bg-red-700",
        Colors.Orange => "hover:bg-orange-700",
        Colors.Amber => "hover:bg-amber-700",
        Colors.Yellow => "hover:bg-yellow-700",
        Colors.Lime => "hover:bg-lime-700",
        Colors.Green => "hover:bg-green-700",
        Colors.Emerald => "hover:bg-emerald-700",
        Colors.Teal => "hover:bg-teal-700",
        Colors.Cyan => "hover:bg-cyan-700",
        Colors.Sky => "hover:bg-sky-700",
        Colors.Blue => "hover:bg-blue-700",
        Colors.Indigo => "hover:bg-indigo-700",
        Colors.Violet => "hover:bg-violet-700",
        Colors.Purple => "hover:bg-purple-700",
        Colors.Fuchsia => "hover:bg-fuchsia-700",
        Colors.Pink => "hover:bg-pink-700",
        Colors.Rose => "hover:bg-rose-700",
        Colors.AthensGray => "hover:bg-athens-gray-700",
        Colors.Woodsmoke => "hover:bg-woodsmoke-700",
        Colors.TurkishRose => "hover:bg-turkish-rose-700",
        _ => ""
    };
    
    public static string ToHoverBackgroundColorWeight800(this Colors color) => color switch
    {
        Colors.Black => "hover:bg-black",
        Colors.White => "hover:bg-white",
        Colors.Slate => "hover:bg-slate-800",
        Colors.Gray => "hover:bg-gray-800",
        Colors.Zinc => "hover:bg-zinc-800",
        Colors.Neutral => "hover:bg-neutral-800",
        Colors.Stone => "hover:bg-stone-800",
        Colors.Red => "hover:bg-red-800",
        Colors.Orange => "hover:bg-orange-800",
        Colors.Amber => "hover:bg-amber-800",
        Colors.Yellow => "hover:bg-yellow-800",
        Colors.Lime => "hover:bg-lime-800",
        Colors.Green => "hover:bg-green-800",
        Colors.Emerald => "hover:bg-emerald-800",
        Colors.Teal => "hover:bg-teal-800",
        Colors.Cyan => "hover:bg-cyan-800",
        Colors.Sky => "hover:bg-sky-800",
        Colors.Blue => "hover:bg-blue-800",
        Colors.Indigo => "hover:bg-indigo-800",
        Colors.Violet => "hover:bg-violet-800",
        Colors.Purple => "hover:bg-purple-800",
        Colors.Fuchsia => "hover:bg-fuchsia-800",
        Colors.Pink => "hover:bg-pink-800",
        Colors.Rose => "hover:bg-rose-800",
        Colors.AthensGray => "hover:bg-athens-gray-800",
        Colors.Woodsmoke => "hover:bg-woodsmoke-800",
        Colors.TurkishRose => "hover:bg-turkish-rose-800",
        _ => ""
    };

    public static string ToRingColorWeight400WithOpacity20(this Colors color) => color switch
    {
        Colors.Black => "ring-black",
        Colors.White => "ring-white",
        Colors.Slate => "ring-slate-400/20",
        Colors.Gray => "ring-gray-400/20",
        Colors.Zinc => "ring-zinc-400/20",
        Colors.Neutral => "ring-neutral-400/20",
        Colors.Stone => "ring-stone-400/20",
        Colors.Red => "ring-red-400/20",
        Colors.Orange => "ring-orange-400/20",
        Colors.Amber => "ring-amber-400/20",
        Colors.Yellow => "ring-yellow-400/20",
        Colors.Lime => "ring-lime-400/20",
        Colors.Green => "ring-green-400/20",
        Colors.Emerald => "ring-emerald-400/20",
        Colors.Teal => "ring-teal-400/20",
        Colors.Cyan => "ring-cyan-400/20",
        Colors.Sky => "ring-sky-400/20",
        Colors.Blue => "ring-blue-400/20",
        Colors.Indigo => "ring-indigo-400/20",
        Colors.Violet => "ring-violet-400/20",
        Colors.Purple => "ring-purple-400/20",
        Colors.Fuchsia => "ring-fuchsia-400/20",
        Colors.Pink => "ring-pink-400/20",
        Colors.Rose => "ring-rose-400/20",
        Colors.AthensGray => "ring-athens-gray-400/20",
        Colors.Woodsmoke => "ring-woodsmoke-400/20",
        Colors.TurkishRose => "ring-turkish-rose-400/20",
        _ => ""
    };
    
    public static string ToRingColorWeight500(this Colors color) => color switch
    {
        Colors.Black => "ring-black",
        Colors.White => "ring-white",
        Colors.Slate => "ring-slate-500",
        Colors.Gray => "ring-gray-500",
        Colors.Zinc => "ring-zinc-500",
        Colors.Neutral => "ring-neutral-500",
        Colors.Stone => "ring-stone-500",
        Colors.Red => "ring-red-500",
        Colors.Orange => "ring-orange-500",
        Colors.Amber => "ring-amber-500",
        Colors.Yellow => "ring-yellow-500",
        Colors.Lime => "ring-lime-500",
        Colors.Green => "ring-green-500",
        Colors.Emerald => "ring-emerald-500",
        Colors.Teal => "ring-teal-500",
        Colors.Cyan => "ring-cyan-500",
        Colors.Sky => "ring-sky-500",
        Colors.Blue => "ring-blue-500",
        Colors.Indigo => "ring-indigo-500",
        Colors.Violet => "ring-violet-500",
        Colors.Purple => "ring-purple-500",
        Colors.Fuchsia => "ring-fuchsia-500",
        Colors.Pink => "ring-pink-500",
        Colors.Rose => "ring-rose-500",
        Colors.AthensGray => "ring-athens-gray-500",
        Colors.Woodsmoke => "ring-woodsmoke-500",
        Colors.TurkishRose => "ring-turkish-rose-500",
        _ => ""
    };
    
    public static string ToRingColorWeight600WithOpacity40(this Colors color) => color switch
    {
        Colors.Black => "ring-black",
        Colors.White => "ring-white",
        Colors.Slate => "ring-slate-600 dark:ring-slate-600/40",
        Colors.Gray => "ring-gray-600 dark:ring-gray-600/40",
        Colors.Zinc => "ring-zinc-600 dark:ring-zinc-600/40",
        Colors.Neutral => "ring-neutral-600 dark:ring-neutral-600/40",
        Colors.Stone => "ring-stone-600 dark:ring-stone-600/40",
        Colors.Red => "ring-red-600 dark:ring-red-600/40",
        Colors.Orange => "ring-orange-600 dark:ring-orange-600/40",
        Colors.Amber => "ring-amber-600 dark:ring-amber-600/40",
        Colors.Yellow => "ring-yellow-600 dark:ring-yellow-600/40",
        Colors.Lime => "ring-lime-600 dark:ring-lime-600/40",
        Colors.Green => "ring-green-600 dark:ring-green-600/40",
        Colors.Emerald => "ring-emerald-600 dark:ring-emerald-600/40",
        Colors.Teal => "ring-teal-600 dark:ring-teal-600/40",
        Colors.Cyan => "ring-cyan-600 dark:ring-cyan-600/40",
        Colors.Sky => "ring-sky-600 dark:ring-sky-600/40",
        Colors.Blue => "ring-blue-600 dark:ring-blue-600/40",
        Colors.Indigo => "ring-indigo-600 dark:ring-indigo-600/40",
        Colors.Violet => "ring-violet-600 dark:ring-violet-600/40",
        Colors.Purple => "ring-purple-600 dark:ring-purple-600/40",
        Colors.Fuchsia => "ring-fuchsia-600 dark:ring-fuchsia-600/40",
        Colors.Pink => "ring-pink-600 dark:ring-pink-600/40",
        Colors.Rose => "ring-rose-600 dark:ring-rose-600/40",
        Colors.AthensGray => "ring-athens-gray-600 dark:ring-athens-gray-600/40",
        Colors.Woodsmoke => "ring-woodsmoke-600 dark:ring-woodsmoke-600/40",
        Colors.TurkishRose => "ring-turkish-rose-600 dark:ring-turkish-rose-600/40",
        _ => ""
    };
    
    public static string ToRingColorWeight700(this Colors color) => color switch
    {
        Colors.Black => "ring-black",
        Colors.White => "ring-white",
        Colors.Slate => "ring-slate-700",
        Colors.Gray => "ring-gray-700",
        Colors.Zinc => "ring-zinc-700",
        Colors.Neutral => "ring-neutral-700",
        Colors.Stone => "ring-stone-700",
        Colors.Red => "ring-red-700",
        Colors.Orange => "ring-orange-700",
        Colors.Amber => "ring-amber-700",
        Colors.Yellow => "ring-yellow-700",
        Colors.Lime => "ring-lime-700",
        Colors.Green => "ring-green-700",
        Colors.Emerald => "ring-emerald-700",
        Colors.Teal => "ring-teal-700",
        Colors.Cyan => "ring-cyan-700",
        Colors.Sky => "ring-sky-700",
        Colors.Blue => "ring-blue-700",
        Colors.Indigo => "ring-indigo-700",
        Colors.Violet => "ring-violet-700",
        Colors.Purple => "ring-purple-700",
        Colors.Fuchsia => "ring-fuchsia-700",
        Colors.Pink => "ring-pink-700",
        Colors.Rose => "ring-rose-700",
        Colors.AthensGray => "ring-athens-gray-700",
        Colors.Woodsmoke => "ring-woodsmoke-700",
        Colors.TurkishRose => "ring-turkish-rose-700",
        _ => ""
    };
    
    public static string ToFocusRingColorWeight500(this Colors color) => color switch
    {
        Colors.Black => "focus:ring-black",
        Colors.White => "focus:ring-white",
        Colors.Slate => "focus:ring-slate-500",
        Colors.Gray => "focus:ring-gray-500",
        Colors.Zinc => "focus:ring-zinc-500",
        Colors.Neutral => "focus:ring-neutral-500",
        Colors.Stone => "focus:ring-stone-500",
        Colors.Red => "focus:ring-red-500",
        Colors.Orange => "focus:ring-orange-500",
        Colors.Amber => "focus:ring-amber-500",
        Colors.Yellow => "focus:ring-yellow-500",
        Colors.Lime => "focus:ring-lime-500",
        Colors.Green => "focus:ring-green-500",
        Colors.Emerald => "focus:ring-emerald-500",
        Colors.Teal => "focus:ring-teal-500",
        Colors.Cyan => "focus:ring-cyan-500",
        Colors.Sky => "focus:ring-sky-500",
        Colors.Blue => "focus:ring-blue-500",
        Colors.Indigo => "focus:ring-indigo-500",
        Colors.Violet => "focus:ring-violet-500",
        Colors.Purple => "focus:ring-purple-500",
        Colors.Fuchsia => "focus:ring-fuchsia-500",
        Colors.Pink => "focus:ring-pink-500",
        Colors.Rose => "focus:ring-rose-500",
        Colors.AthensGray => "focus:ring-athens-gray-500",
        Colors.Woodsmoke => "focus:ring-woodsmoke-500",
        Colors.TurkishRose => "focus:ring-turkish-rose-500",
        _ => ""
    };

}
