using Railwind.Enums;

namespace Railwind.Common.Extensions;

public static class MaxWidthExtensions
{
    public static string ToCssClass(this MaxWidth value) => ((MaxWidth?)value).ToCssClass();

    public static string ToCssClass(this MaxWidth? value) => value switch
    {
        MaxWidth.Zero => "max-w-0",
        MaxWidth.One => "max-w-1",
        MaxWidth.Two => "max-w-2",
        MaxWidth.Three => "max-w-3",
        MaxWidth.Four => "max-w-4",
        MaxWidth.Five => "max-w-5",
        MaxWidth.Six => "max-w-6",
        MaxWidth.Seven => "max-w-7",
        MaxWidth.Eight => "max-w-8",
        MaxWidth.Nine => "max-w-9",
        MaxWidth.Ten => "max-w-10",
        MaxWidth.Eleven => "max-w-11",
        MaxWidth.Twelve => "max-w-12",
        MaxWidth.Fourteen => "max-w-14",
        MaxWidth.Sixteen => "max-w-16",
        MaxWidth.Twenty => "max-w-20",
        MaxWidth.TwentyFour => "max-w-24",
        MaxWidth.TwentyEight => "max-w-28",
        MaxWidth.ThirtyTwo => "max-w-32",
        MaxWidth.ThirtySix => "max-w-36",
        MaxWidth.Forty => "max-w-40",
        MaxWidth.FortyFour => "max-w-44",
        MaxWidth.FortyEight => "max-w-48",
        MaxWidth.FiftyTwo => "max-w-52",
        MaxWidth.FiftySix => "max-w-56",
        MaxWidth.Sixty => "max-w-60",
        MaxWidth.SixtyFour => "max-w-64",
        MaxWidth.SeventyTwo => "max-w-72",
        MaxWidth.Eighty => "max-w-80",
        MaxWidth.NinetySix => "max-w-96",
        MaxWidth.ZeroPointFive => "max-w-0.5",
        MaxWidth.OnePointFive => "max-w-1.5",
        MaxWidth.TwoPointFive => "max-w-2.5",
        MaxWidth.ThreePointFive => "max-w-3.5",
        MaxWidth.Full => "max-w-full",
        MaxWidth.ThreeXs => "max-w-3xs",
        MaxWidth.TwoXs => "max-w-2xs",
        MaxWidth.Xs => "max-w-xs",
        MaxWidth.Sm => "max-w-sm",
        MaxWidth.Md => "max-w-md",
        MaxWidth.Lg => "max-w-lg",
        MaxWidth.Xl => "max-w-xl",
        MaxWidth.TwoXl => "max-w-2xl",
        MaxWidth.ThreeXl => "max-w-3xl",
        MaxWidth.FourXl => "max-w-4xl",
        MaxWidth.FiveXl => "max-w-5xl",
        MaxWidth.SixXl => "max-w-6xl",
        MaxWidth.SevenXl => "max-w-7xl",
        _ => "max-w-0"
    };
    
     public static string ToMdCssClass(this MaxWidth value) => ((MaxWidth?)value).ToMdCssClass();

    public static string ToMdCssClass(this MaxWidth? value) => value switch
    {
        MaxWidth.Zero => "md:max-w-0",
        MaxWidth.One => "md:max-w-1",
        MaxWidth.Two => "md:max-w-2",
        MaxWidth.Three => "md:max-w-3",
        MaxWidth.Four => "md:max-w-4",
        MaxWidth.Five => "md:max-w-5",
        MaxWidth.Six => "md:max-w-6",
        MaxWidth.Seven => "md:max-w-7",
        MaxWidth.Eight => "md:max-w-8",
        MaxWidth.Nine => "md:max-w-9",
        MaxWidth.Ten => "md:max-w-10",
        MaxWidth.Eleven => "md:max-w-11",
        MaxWidth.Twelve => "md:max-w-12",
        MaxWidth.Fourteen => "md:max-w-14",
        MaxWidth.Sixteen => "md:max-w-16",
        MaxWidth.Twenty => "md:max-w-20",
        MaxWidth.TwentyFour => "md:max-w-24",
        MaxWidth.TwentyEight => "md:max-w-28",
        MaxWidth.ThirtyTwo => "md:max-w-32",
        MaxWidth.ThirtySix => "md:max-w-36",
        MaxWidth.Forty => "md:max-w-40",
        MaxWidth.FortyFour => "md:max-w-44",
        MaxWidth.FortyEight => "md:max-w-48",
        MaxWidth.FiftyTwo => "md:max-w-52",
        MaxWidth.FiftySix => "md:max-w-56",
        MaxWidth.Sixty => "md:max-w-60",
        MaxWidth.SixtyFour => "md:max-w-64",
        MaxWidth.SeventyTwo => "md:max-w-72",
        MaxWidth.Eighty => "md:max-w-80",
        MaxWidth.NinetySix => "md:max-w-96",
        MaxWidth.ZeroPointFive => "md:max-w-0.5",
        MaxWidth.OnePointFive => "md:max-w-1.5",
        MaxWidth.TwoPointFive => "md:max-w-2.5",
        MaxWidth.ThreePointFive => "md:max-w-3.5",
        MaxWidth.Full => "md:max-w-full",
        MaxWidth.ThreeXs => "md:max-w-3xs",
        MaxWidth.TwoXs => "md:max-w-2xs",
        MaxWidth.Xs => "md:max-w-xs",
        MaxWidth.Sm => "md:max-w-sm",
        MaxWidth.Md => "md:max-w-md",
        MaxWidth.Lg => "md:max-w-lg",
        MaxWidth.Xl => "md:max-w-xl",
        MaxWidth.TwoXl => "md:max-w-2xl",
        MaxWidth.ThreeXl => "md:max-w-3xl",
        MaxWidth.FourXl => "md:max-w-4xl",
        MaxWidth.FiveXl => "md:max-w-5xl",
        MaxWidth.SixXl => "md:max-w-6xl",
        MaxWidth.SevenXl => "md:max-w-7xl",
        _ => ""
    };
}