using Railwind.Enums;

namespace Railwind.Common.Extensions;

public static class MaxWidthExtensions
{
    public static string ToMaxWidthCssClass(this Width value) => ((Width?)value).ToMaxWidthCssClass();

    public static string ToMaxWidthCssClass(this Width? value) => value switch
    {
        Width.Zero => "max-w-0",
        Width.One => "max-w-1",
        Width.Two => "max-w-2",
        Width.Three => "max-w-3",
        Width.Four => "max-w-4",
        Width.Five => "max-w-5",
        Width.Six => "max-w-6",
        Width.Seven => "max-w-7",
        Width.Eight => "max-w-8",
        Width.Nine => "max-w-9",
        Width.Ten => "max-w-10",
        Width.Eleven => "max-w-11",
        Width.Twelve => "max-w-12",
        Width.Fourteen => "max-w-14",
        Width.Sixteen => "max-w-16",
        Width.Twenty => "max-w-20",
        Width.TwentyFour => "max-w-24",
        Width.TwentyEight => "max-w-28",
        Width.ThirtyTwo => "max-w-32",
        Width.ThirtySix => "max-w-36",
        Width.Forty => "max-w-40",
        Width.FortyFour => "max-w-44",
        Width.FortyEight => "max-w-48",
        Width.FiftyTwo => "max-w-52",
        Width.FiftySix => "max-w-56",
        Width.Sixty => "max-w-60",
        Width.SixtyFour => "max-w-64",
        Width.SeventyTwo => "max-w-72",
        Width.Eighty => "max-w-80",
        Width.NinetySix => "max-w-96",
        Width.ZeroPointFive => "max-w-0.5",
        Width.OnePointFive => "max-w-1.5",
        Width.TwoPointFive => "max-w-2.5",
        Width.ThreePointFive => "max-w-3.5",
        Width.Full => "max-w-full",
        Width.ThreeXs => "max-w-3xs",
        Width.TwoXs => "max-w-2xs",
        Width.Xs => "max-w-xs",
        Width.Sm => "max-w-sm",
        Width.Md => "max-w-md",
        Width.Lg => "max-w-lg",
        Width.Xl => "max-w-xl",
        Width.TwoXl => "max-w-2xl",
        Width.ThreeXl => "max-w-3xl",
        Width.FourXl => "max-w-4xl",
        Width.FiveXl => "max-w-5xl",
        Width.SixXl => "max-w-6xl",
        Width.SevenXl => "max-w-7xl",
        Width.Half => "max-w-1/2",
        _ => ""
    };
    
    public static string ToWidthCssClass(this Width value) => ((Width?)value).ToWidthCssClass();
    
    public static string ToWidthCssClass(this Width? value) => value switch
    {
        Width.Zero => "w-0",
        Width.One => "w-1",
        Width.Two => "w-2",
        Width.Three => "w-3",
        Width.Four => "w-4",
        Width.Five => "w-5",
        Width.Six => "w-6",
        Width.Seven => "w-7",
        Width.Eight => "w-8",
        Width.Nine => "w-9",
        Width.Ten => "w-10",
        Width.Eleven => "w-11",
        Width.Twelve => "w-12",
        Width.Fourteen => "w-14",
        Width.Sixteen => "w-16",
        Width.Twenty => "w-20",
        Width.TwentyFour => "w-24",
        Width.TwentyEight => "w-28",
        Width.ThirtyTwo => "w-32",
        Width.ThirtySix => "w-36",
        Width.Forty => "w-40",
        Width.FortyFour => "w-44",
        Width.FortyEight => "w-48",
        Width.FiftyTwo => "w-52",
        Width.FiftySix => "w-56",
        Width.Sixty => "w-60",
        Width.SixtyFour => "w-64",
        Width.SeventyTwo => "w-72",
        Width.Eighty => "w-80",
        Width.NinetySix => "w-96",
        Width.ZeroPointFive => "w-0.5",
        Width.OnePointFive => "w-1.5",
        Width.TwoPointFive => "w-2.5",
        Width.ThreePointFive => "w-3.5",
        Width.Full => "w-full",
        Width.ThreeXs => "w-3xs",
        Width.TwoXs => "w-2xs",
        Width.Xs => "w-xs",
        Width.Sm => "w-sm",
        Width.Md => "w-md",
        Width.Lg => "w-lg",
        Width.Xl => "w-xl",
        Width.TwoXl => "w-2xl",
        Width.ThreeXl => "w-3xl",
        Width.FourXl => "w-4xl",
        Width.FiveXl => "w-5xl",
        Width.SixXl => "w-6xl",
        Width.SevenXl => "w-7xl",
        Width.Half => "w-1/2",
        _ => ""
    };
    
     public static string ToMdMaxWidthCssClass(this Width value) => ((Width?)value).ToMdMaxWidthCssClass();

    public static string ToMdMaxWidthCssClass(this Width? value) => value switch
    {
        Width.Zero => "md:max-w-0",
        Width.One => "md:max-w-1",
        Width.Two => "md:max-w-2",
        Width.Three => "md:max-w-3",
        Width.Four => "md:max-w-4",
        Width.Five => "md:max-w-5",
        Width.Six => "md:max-w-6",
        Width.Seven => "md:max-w-7",
        Width.Eight => "md:max-w-8",
        Width.Nine => "md:max-w-9",
        Width.Ten => "md:max-w-10",
        Width.Eleven => "md:max-w-11",
        Width.Twelve => "md:max-w-12",
        Width.Fourteen => "md:max-w-14",
        Width.Sixteen => "md:max-w-16",
        Width.Twenty => "md:max-w-20",
        Width.TwentyFour => "md:max-w-24",
        Width.TwentyEight => "md:max-w-28",
        Width.ThirtyTwo => "md:max-w-32",
        Width.ThirtySix => "md:max-w-36",
        Width.Forty => "md:max-w-40",
        Width.FortyFour => "md:max-w-44",
        Width.FortyEight => "md:max-w-48",
        Width.FiftyTwo => "md:max-w-52",
        Width.FiftySix => "md:max-w-56",
        Width.Sixty => "md:max-w-60",
        Width.SixtyFour => "md:max-w-64",
        Width.SeventyTwo => "md:max-w-72",
        Width.Eighty => "md:max-w-80",
        Width.NinetySix => "md:max-w-96",
        Width.ZeroPointFive => "md:max-w-0.5",
        Width.OnePointFive => "md:max-w-1.5",
        Width.TwoPointFive => "md:max-w-2.5",
        Width.ThreePointFive => "md:max-w-3.5",
        Width.Full => "md:max-w-full",
        Width.ThreeXs => "md:max-w-3xs",
        Width.TwoXs => "md:max-w-2xs",
        Width.Xs => "md:max-w-xs",
        Width.Sm => "md:max-w-sm",
        Width.Md => "md:max-w-md",
        Width.Lg => "md:max-w-lg",
        Width.Xl => "md:max-w-xl",
        Width.TwoXl => "md:max-w-2xl",
        Width.ThreeXl => "md:max-w-3xl",
        Width.FourXl => "md:max-w-4xl",
        Width.FiveXl => "md:max-w-5xl",
        Width.SixXl => "md:max-w-6xl",
        Width.SevenXl => "md:max-w-7xl",
        Width.Half => "md:max-w-1/2",
        _ => ""
    };
}